variables:
    - variable:  
        name: tempa
        host: 10.0.20.1
        port: 5020
        type: co
        address: 1
        size: 1 
    - variable:
        name: tempb
        host: 10.0.30.1
        port: 5020
        type: co
        address: 1
        size: 1 

requirements:
    - requirement: tempa > 1 & tempb > 1
      
