variables:
    - variable:  
        name: temp1
        host: 10.0.20.1
        port: 5020
        type: co
        address: 1
        size: 1 
    - variable:
        name: temp2
        host: 10.0.30.1
        port: 5020
        type: co
        address: 1
        size: 1 

requirements:
    - requirement: 2*temp1 + 3*temp2 > 4
      
