/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "IDSController_constants.h"

namespace IDSControllerCpp {

const IDSControllerConstants g_IDSController_constants;

IDSControllerConstants::IDSControllerConstants() {
}

} // namespace

