/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef IDSController_CONSTANTS_H
#define IDSController_CONSTANTS_H

#include "IDSController_types.h"

namespace IDSControllerCpp {

class IDSControllerConstants {
 public:
  IDSControllerConstants();

};

extern const IDSControllerConstants g_IDSController_constants;

} // namespace

#endif
