variables:
    - variable:
        name: tanka
        host: 10.0.20.7
        port: 5020
        type: hr
        address: 0
        size: 1

    - variable:
        name: valvecharcoal
        host: 10.0.20.15
        port: 5020
        type: co
        address: 0
        size: 1
    
    - variable:
        name: wagoncar
        host: 10.0.20.13
        port: 5020
        type: hr
        address: 0
        size: 1

    - variable:
        name: wagonend
        host: 10.0.20.14
        port: 5020
        type: co
        address: 0
        size: 1

    - variable:
        name: tankfinal
        host: 10.0.20.21
        port: 5020
        type: hr
        address: 0
        size: 1

    - variable:
        name: motora
        host: 10.0.20.4
        port: 5020
        type: co
        address: 0
        size: 1

    - variable:
        name: motorb
        host: 10.0.20.9
        port: 5020
        type: co
        address: 0
        size: 1

    - variable:
        name: silob
        host: 10.0.20.19
        port: 5020
        type: hr
        address: 0
        size: 1

requirements:
    - requirement: tanka >= 60 
    - requirement: wagoncar >= 40 
    - requirement: silob >= 80
    - requirement: tankfinal >= 80
    - requirement: wagonend = 1 & valvecharcoal = 1 
